#include "memory_map.h"
#include "kernel_mmio_conv3d.h"
#include "nn.h"

#define CORE_ID 0
#define NUM_CORES 9

#define CONV3D_CORE_ID 0
#define CONV3D_NUM_CORES 4

#define LINEAR_CORE_ID_START 4

void sync_with_conv3d_cores() {
  for (int c = 1; c < CONV3D_NUM_CORES; c++) {
    while (SYNC(c) == 0);
    SYNC(c) = 0;
  }

  long long int socket_addr = SOCKET1_NOC_ADDR;
  for (int c = 1; c < CONV3D_NUM_CORES; c++) {
    CTRL_MAXI_SOCKET_OFFSET_LO = ((socket_addr + MMIO_REGSPACE_OFFSET) & 0xFFFFFFFF) + SYNC_OFFSET(CORE_ID); 
    CTRL_MAXI_SOCKET_OFFSET_HI = ((socket_addr + MMIO_REGSPACE_OFFSET) >> 32);
    CTRL_MAXI_WRITE = 1;
    while (CTRL_MAXI_WRITE_DONE == 0);
    socket_addr += 0x40000000;
    if (c == 3)
      socket_addr += 0x40000000;
  }
}

void sync_with_linear_master_core() {
  while (SYNC(LINEAR_CORE_ID_START) == 0);
  SYNC(LINEAR_CORE_ID_START) = 0;

  long long int socket_addr = SOCKET4_NOC_ADDR;
  CTRL_MAXI_SOCKET_OFFSET_LO = ((socket_addr + MMIO_REGSPACE_OFFSET) & 0xFFFFFFFF) + SYNC_OFFSET(CORE_ID); 
  CTRL_MAXI_SOCKET_OFFSET_HI = ((socket_addr + MMIO_REGSPACE_OFFSET) >> 32);
  CTRL_MAXI_WRITE = 1;
  while (CTRL_MAXI_WRITE_DONE == 0);
}

int main() {
  long long int ext_mem_offset;

  LSU0_RAM_STRIDE = 1;
  LSU0_RAM_SEG_STRIDE = 1;
  LSU0_RAM_ADDR_OFFSET = 0;
  LSU0_M_OFFSET_HI = 0;
  LSU0_SEG_STRIDE = 0;
  LSU0_SEG_COUNT = 1;

  LSU1_RAM_STRIDE = 1;
  LSU1_RAM_SEG_STRIDE = 1;
  LSU1_RAM_ADDR_OFFSET = 0;
  LSU1_M_OFFSET_HI = 0;
  LSU1_SEG_STRIDE = 0;
  LSU1_SEG_COUNT = 1;

  for (int i = CONV3D_CORE_ID*CONV3D_OFM_CNT; i < CONV3D0_OFM_CHN; i+=CONV3D_NUM_CORES*CONV3D_OFM_CNT) {
    // fetch ofm
    LSU0_RAM_START_IDX = 16;
    LSU0_RAM_ADDR_OFFSET = 0;
    LSU0_RAM_BLOCK_FACTOR = CONV3D_OFM_CNT * CONV3D0_OFM_SIZE_CEIL / LSU_WIDTH_SCALE;
    LSU0_RAM_CYCLIC_FACTOR = 1;
    ext_mem_offset = EXT_MEM_OFFSET + ((CONV3D0_WT_LEN + CONV3D0_IFM_LEN + i * CONV3D0_OFM_SIZE_CEIL) << LOG2_WORD_SIZE);
    LSU0_M_OFFSET_LO = (ext_mem_offset & 0xFFFFFFFF);
    LSU0_M_OFFSET_HI = (ext_mem_offset >> 32);
    LSU0_SEG_STRIDE = 0;
    LSU0_SEG_COUNT = 1;
    LSU0_LEN = CONV3D_OFM_CNT * CONV3D0_OFM_SIZE_CEIL / WORD_SCALE;
    LSU0_MODE = 1;

    TQ_LSU0_START();
    TQ_LSU0_DONE();

    // fetch weight
    LSU1_RAM_START_IDX = 0;
    LSU1_RAM_ADDR_OFFSET = 0;
    LSU1_RAM_BLOCK_FACTOR = CONV3D0_WT_SIZE_CEIL / LSU_WIDTH_SCALE;
    LSU1_RAM_CYCLIC_FACTOR = CONV3D_NUM_CONV2D;

    ext_mem_offset = EXT_MEM_OFFSET + ((CONV3D0_IFM_LEN + i * CONV3D0_IFM_CHN * CONV3D0_WT_SIZE_CEIL + 0 * CONV3D0_WT_SIZE_CEIL) << LOG2_WORD_SIZE);
    LSU1_M_OFFSET_LO = (ext_mem_offset & 0xFFFFFFFF);
    LSU1_M_OFFSET_HI = (ext_mem_offset >> 32);
    LSU1_SEG_STRIDE = CONV3D0_IFM_CHN * CONV3D0_WT_SIZE_CEIL / WORD_SCALE;
    LSU1_SEG_COUNT = CONV3D_OFM_CNT;
    LSU1_LEN = CONV3D_NUM_CONV2D * CONV3D0_WT_SIZE_CEIL / WORD_SCALE;
    LSU1_MODE = 1;

    TQ_LSU1_START();

    // fetch ifm
    LSU0_RAM_START_IDX = 8;
    LSU0_RAM_ADDR_OFFSET = 0;
    LSU0_SEG_STRIDE = 0;
    LSU0_SEG_COUNT = 1;
    LSU0_RAM_BLOCK_FACTOR = CONV3D0_IFM_SIZE_CEIL / LSU_WIDTH_SCALE;
    LSU0_RAM_CYCLIC_FACTOR = CONV3D_NUM_CONV2D;

    ext_mem_offset = EXT_MEM_OFFSET + ((0 * CONV3D0_IFM_SIZE_CEIL) << LOG2_WORD_SIZE);
    LSU0_M_OFFSET_LO = (ext_mem_offset & 0xFFFFFFFF);
    LSU0_M_OFFSET_HI = (ext_mem_offset >> 32);
    LSU0_LEN = CONV3D_NUM_CONV2D * CONV3D0_IFM_SIZE_CEIL / WORD_SCALE;
    LSU0_MODE = 1;

    TQ_LSU0_START();

    TQ_LSU0_DONE();
    TQ_LSU1_DONE();
    int pp = 0;
    for (int j = 0; j < CONV3D0_IFM_CHN; j+=CONV3D_NUM_CONV2D) {
      int len = (j < CONV3D0_IFM_CHN_SCALE * CONV3D_NUM_CONV2D) ? CONV3D_NUM_CONV2D : (CONV3D0_IFM_CHN - CONV3D0_IFM_CHN_SCALE * CONV3D_NUM_CONV2D);

      if (j + CONV3D_NUM_CONV2D < CONV3D0_IFM_CHN) {
      // fetch weight
      LSU1_RAM_START_IDX = 0;
      LSU1_RAM_ADDR_OFFSET = (pp == 0) ? (CONV3D_OFM_CNT * CONV3D0_WT_SIZE_CEIL / LSU_WIDTH_SCALE) : 0;
      LSU1_RAM_BLOCK_FACTOR = CONV3D0_WT_SIZE_CEIL / LSU_WIDTH_SCALE;
      LSU1_RAM_CYCLIC_FACTOR = CONV3D_NUM_CONV2D;

      ext_mem_offset = EXT_MEM_OFFSET + ((CONV3D0_IFM_LEN + i * CONV3D0_IFM_CHN * CONV3D0_WT_SIZE_CEIL + (j + CONV3D_NUM_CONV2D) * CONV3D0_WT_SIZE_CEIL) << LOG2_WORD_SIZE);
      LSU1_M_OFFSET_LO = (ext_mem_offset & 0xFFFFFFFF);
      LSU1_M_OFFSET_HI = (ext_mem_offset >> 32);
      LSU1_SEG_STRIDE = CONV3D0_IFM_CHN * CONV3D0_WT_SIZE_CEIL / WORD_SCALE;
      LSU1_SEG_COUNT = CONV3D_OFM_CNT;
      LSU1_LEN = CONV3D_NUM_CONV2D * CONV3D0_WT_SIZE_CEIL / WORD_SCALE;
      LSU1_MODE = 1;

      TQ_LSU1_START();

      // fetch ifm
      LSU0_RAM_START_IDX = 8;
      LSU0_RAM_ADDR_OFFSET = (pp == 0) ? CONV3D0_IFM_SIZE_CEIL / LSU_WIDTH_SCALE : 0;
      LSU0_SEG_STRIDE = 0;
      LSU0_SEG_COUNT = 1;
      LSU0_RAM_BLOCK_FACTOR = CONV3D0_IFM_SIZE_CEIL / LSU_WIDTH_SCALE;
      LSU0_RAM_CYCLIC_FACTOR = CONV3D_NUM_CONV2D;

      ext_mem_offset = EXT_MEM_OFFSET + (((j + CONV3D_NUM_CONV2D) * CONV3D0_IFM_SIZE_CEIL) << LOG2_WORD_SIZE);
      LSU0_M_OFFSET_LO = (ext_mem_offset & 0xFFFFFFFF);
      LSU0_M_OFFSET_HI = (ext_mem_offset >> 32);
      LSU0_LEN = CONV3D_NUM_CONV2D * CONV3D0_IFM_SIZE_CEIL / WORD_SCALE;
      LSU0_MODE = 1;

      TQ_LSU0_START();
      }

      KRN_IFM_OFFSET = (pp == 0) ? 0 : CONV3D0_IFM_SIZE_CEIL / LSU_WIDTH_SCALE;
      for (int k = 0; k < CONV3D_OFM_CNT; k++) {
        KRN_WT_OFFSET = ((pp == 0) ? 0 : (CONV3D_OFM_CNT * CONV3D0_WT_SIZE_CEIL / LSU_WIDTH_SCALE)) + (k * CONV3D0_WT_SIZE_CEIL / LSU_WIDTH_SCALE);
        KRN_OFM_OFFSET = k * CONV3D0_OFM_SIZE_CEIL / LSU_WIDTH_SCALE;
        KRN_LEN = len;
        KRN_STATE = 1;
        KRN_START = 1;
        TQ_CL_START();
        TQ_CL_DONE();
      }

      if (j + CONV3D_NUM_CONV2D < CONV3D0_IFM_CHN) {
        TQ_LSU0_DONE();
        TQ_LSU1_DONE();
      }
      pp = 1 - pp;
    }

//    // maxpool
//    for (int k = 0; k < CONV3D_OFM_CNT; k++) {
//      KRN_IFM_OFFSET = k * CONV3D0_OFM_SIZE_CEIL / LSU_WIDTH_SCALE;
//      KRN_OFM_OFFSET = k * CONV3D0_OFM_SIZE_CEIL / LSU_WIDTH_SCALE;
//      KRN_STATE = 2;
//      KRN_START = 1;
//      TQ_CL_START();
//      TQ_CL_DONE();
//    }

    // write ofm
    LSU0_RAM_START_IDX = 16;
    LSU0_RAM_ADDR_OFFSET = 0;
    LSU0_RAM_BLOCK_FACTOR = CONV3D_OFM_CNT * CONV3D0_OFM_SIZE_CEIL / LSU_WIDTH_SCALE;
    LSU0_RAM_CYCLIC_FACTOR = 1;
    ext_mem_offset = EXT_MEM_OFFSET + ((CONV3D0_WT_LEN + CONV3D0_IFM_LEN + i * CONV3D0_OFM_SIZE_CEIL) << LOG2_WORD_SIZE);
    LSU0_M_OFFSET_LO = (ext_mem_offset & 0xFFFFFFFF);
    LSU0_M_OFFSET_HI = (ext_mem_offset >> 32);
    LSU0_SEG_STRIDE = 0;
    LSU0_SEG_COUNT = 1;
    LSU0_LEN = CONV3D_OFM_CNT * CONV3D0_OFM_SIZE_CEIL / WORD_SCALE;
    LSU0_MODE = 2;

    TQ_LSU0_START();
    TQ_LSU0_DONE();
  }

  while (TQ_EMPTY_N == 1);

  sync_with_conv3d_cores();

  for (int i = CONV3D_CORE_ID*CONV3D_OFM_CNT; i < CONV3D1_OFM_CHN; i+=CONV3D_NUM_CORES*CONV3D_OFM_CNT) {
    // fetch ofm
    LSU0_RAM_START_IDX = 16;
    LSU0_RAM_ADDR_OFFSET = 0;
    LSU0_RAM_BLOCK_FACTOR = CONV3D_OFM_CNT * CONV3D1_OFM_SIZE_CEIL / LSU_WIDTH_SCALE;
    LSU0_RAM_CYCLIC_FACTOR = 1;
    ext_mem_offset = EXT_MEM_OFFSET + ((CONV3D1_MEM_OFFSET + CONV3D1_IFM_LEN + CONV3D1_WT_LEN + i * CONV3D1_OFM_SIZE_CEIL) << LOG2_WORD_SIZE);
    LSU0_M_OFFSET_LO = (ext_mem_offset & 0xFFFFFFFF);
    LSU0_M_OFFSET_HI = (ext_mem_offset >> 32);
    LSU0_SEG_STRIDE = 0;
    LSU0_SEG_COUNT = 1;
    LSU0_LEN = CONV3D_OFM_CNT * CONV3D1_OFM_SIZE_CEIL / WORD_SCALE;
    LSU0_MODE = 1;

    TQ_LSU0_START();
    TQ_LSU0_DONE();

    // fetch weight
    LSU1_RAM_START_IDX = 0;
    LSU1_RAM_ADDR_OFFSET = 0;
    LSU1_RAM_BLOCK_FACTOR = CONV3D1_WT_SIZE_CEIL / LSU_WIDTH_SCALE;
    LSU1_RAM_CYCLIC_FACTOR = CONV3D_NUM_CONV2D;

    ext_mem_offset = EXT_MEM_OFFSET + ((CONV3D1_MEM_OFFSET + CONV3D1_IFM_LEN + i * CONV3D1_IFM_CHN * CONV3D1_WT_SIZE_CEIL + 0 * CONV3D1_WT_SIZE_CEIL) << LOG2_WORD_SIZE);
    LSU1_M_OFFSET_LO = (ext_mem_offset & 0xFFFFFFFF);
    LSU1_M_OFFSET_HI = (ext_mem_offset >> 32);
    LSU1_SEG_STRIDE = CONV3D1_IFM_CHN * CONV3D1_WT_SIZE_CEIL / WORD_SCALE;
    LSU1_SEG_COUNT = CONV3D_OFM_CNT;
    LSU1_LEN = CONV3D_NUM_CONV2D * CONV3D1_WT_SIZE_CEIL / WORD_SCALE;
    LSU1_MODE = 1;

    TQ_LSU1_START();

    // fetch ifm
    LSU0_RAM_START_IDX = 8;
    LSU0_RAM_ADDR_OFFSET = 0;
    LSU0_SEG_STRIDE = 0;
    LSU0_SEG_COUNT = 1;
    LSU0_RAM_BLOCK_FACTOR = CONV3D1_IFM_SIZE_CEIL / LSU_WIDTH_SCALE;
    LSU0_RAM_CYCLIC_FACTOR = CONV3D_NUM_CONV2D;

    ext_mem_offset = EXT_MEM_OFFSET + ((CONV3D1_MEM_OFFSET + 0 * CONV3D1_IFM_SIZE_CEIL) << LOG2_WORD_SIZE);
    LSU0_M_OFFSET_LO = (ext_mem_offset & 0xFFFFFFFF);
    LSU0_M_OFFSET_HI = (ext_mem_offset >> 32);
    LSU0_LEN = CONV3D_NUM_CONV2D * CONV3D1_IFM_SIZE_CEIL / WORD_SCALE;
    LSU0_MODE = 1;

    TQ_LSU0_START();

    TQ_LSU0_DONE();
    TQ_LSU1_DONE();
    int pp = 0;
    for (int j = 0; j < CONV3D1_IFM_CHN; j+=CONV3D_NUM_CONV2D) {
      int len = (j < CONV3D1_IFM_CHN_SCALE * CONV3D_NUM_CONV2D) ? CONV3D_NUM_CONV2D : (CONV3D1_IFM_CHN - CONV3D1_IFM_CHN_SCALE * CONV3D_NUM_CONV2D);

      if (j + CONV3D_NUM_CONV2D < CONV3D1_IFM_CHN) {
      // fetch weight
      LSU1_RAM_START_IDX = 0;
      LSU1_RAM_ADDR_OFFSET = (pp == 0) ? (CONV3D_OFM_CNT * CONV3D1_WT_SIZE_CEIL / LSU_WIDTH_SCALE) : 0;
      LSU1_RAM_BLOCK_FACTOR = CONV3D1_WT_SIZE_CEIL / LSU_WIDTH_SCALE;
      LSU1_RAM_CYCLIC_FACTOR = CONV3D_NUM_CONV2D;

      ext_mem_offset = EXT_MEM_OFFSET + ((CONV3D1_MEM_OFFSET + CONV3D1_IFM_LEN + i * CONV3D1_IFM_CHN * CONV3D1_WT_SIZE_CEIL + (j + CONV3D_NUM_CONV2D) * CONV3D1_WT_SIZE_CEIL) << LOG2_WORD_SIZE);
      LSU1_M_OFFSET_LO = (ext_mem_offset & 0xFFFFFFFF);
      LSU1_M_OFFSET_HI = (ext_mem_offset >> 32);
      LSU1_SEG_STRIDE = CONV3D1_IFM_CHN * CONV3D1_WT_SIZE_CEIL / WORD_SCALE;
      LSU1_SEG_COUNT = CONV3D_OFM_CNT;
      LSU1_LEN = CONV3D_NUM_CONV2D * CONV3D1_WT_SIZE_CEIL / WORD_SCALE;
      LSU1_MODE = 1;

      TQ_LSU1_START();

      // fetch ifm
      LSU0_RAM_START_IDX = 8;
      LSU0_RAM_ADDR_OFFSET = (pp == 0) ? CONV3D1_IFM_SIZE_CEIL / LSU_WIDTH_SCALE : 0;
      LSU0_SEG_STRIDE = 0;
      LSU0_SEG_COUNT = 1;
      LSU0_RAM_BLOCK_FACTOR = CONV3D1_IFM_SIZE_CEIL / LSU_WIDTH_SCALE;
      LSU0_RAM_CYCLIC_FACTOR = CONV3D_NUM_CONV2D;

      ext_mem_offset = EXT_MEM_OFFSET + ((CONV3D1_MEM_OFFSET + (j + CONV3D_NUM_CONV2D) * CONV3D1_IFM_SIZE_CEIL) << LOG2_WORD_SIZE);
      LSU0_M_OFFSET_LO = (ext_mem_offset & 0xFFFFFFFF);
      LSU0_M_OFFSET_HI = (ext_mem_offset >> 32);
      LSU0_LEN = CONV3D_NUM_CONV2D * CONV3D1_IFM_SIZE_CEIL / WORD_SCALE;
      LSU0_MODE = 1;

      TQ_LSU0_START();
      }

      KRN_IFM_OFFSET = (pp == 0) ? 0 : CONV3D1_IFM_SIZE_CEIL / LSU_WIDTH_SCALE;
      for (int k = 0; k < CONV3D_OFM_CNT; k++) {
        KRN_WT_OFFSET = ((pp == 0) ? 0 : (CONV3D_OFM_CNT * CONV3D1_WT_SIZE_CEIL / LSU_WIDTH_SCALE)) + (k * CONV3D1_WT_SIZE_CEIL / LSU_WIDTH_SCALE);
        KRN_OFM_OFFSET = k * CONV3D1_OFM_SIZE_CEIL / LSU_WIDTH_SCALE;
        KRN_LEN = len;
        KRN_STATE = 1;
        KRN_START = 1;
        TQ_CL_START();
        TQ_CL_DONE();
      }

      if (j + CONV3D_NUM_CONV2D < CONV3D1_IFM_CHN) {
        TQ_LSU0_DONE();
        TQ_LSU1_DONE();
      }
      pp = 1 - pp;
    }

//    // maxpool
//    for (int k = 0; k < CONV3D_OFM_CNT; k++) {
//      KRN_IFM_OFFSET = k * CONV3D1_OFM_SIZE_CEIL / LSU_WIDTH_SCALE;
//      KRN_OFM_OFFSET = k * CONV3D1_OFM_SIZE_CEIL / LSU_WIDTH_SCALE;
//      KRN_STATE = 2;
//      KRN_START = 1;
//      TQ_CL_START();
//      TQ_CL_DONE();
//    }

    // write ofm
    LSU0_RAM_START_IDX = 16;
    LSU0_RAM_ADDR_OFFSET = 0;
    LSU0_RAM_BLOCK_FACTOR = CONV3D_OFM_CNT * CONV3D1_OFM_SIZE_CEIL / LSU_WIDTH_SCALE;
    LSU0_RAM_CYCLIC_FACTOR = 1;
    ext_mem_offset = EXT_MEM_OFFSET + ((CONV3D1_MEM_OFFSET + CONV3D1_WT_LEN + CONV3D1_IFM_LEN + i * CONV3D1_OFM_SIZE_CEIL) << LOG2_WORD_SIZE);
    LSU0_M_OFFSET_LO = (ext_mem_offset & 0xFFFFFFFF);
    LSU0_M_OFFSET_HI = (ext_mem_offset >> 32);
    LSU0_SEG_STRIDE = 0;
    LSU0_SEG_COUNT = 1;
    LSU0_LEN = CONV3D_OFM_CNT * CONV3D1_OFM_SIZE_CEIL / WORD_SCALE;
    LSU0_MODE = 2;

    TQ_LSU0_START();
    TQ_LSU0_DONE();
  }

  while (TQ_EMPTY_N == 1);

  sync_with_conv3d_cores();

  sync_with_linear_master_core();

  CTRL_MAXI_SOCKET_OFFSET_LO = ((SOCKET_MANAGER_NOC_ADDR + MMIO_REGSPACE_OFFSET) & 0xFFFFFFFF) + ((128 + CORE_ID)<<6); 
  CTRL_MAXI_SOCKET_OFFSET_HI = ((SOCKET_MANAGER_NOC_ADDR + MMIO_REGSPACE_OFFSET) >> 32);
  CTRL_MAXI_WRITE = 1;
  while (CTRL_MAXI_WRITE_DONE == 0);

  CPU_STATUS = 1;

  // spin
  for(;;) {
    asm volatile ("nop");
  }
}
