#include "memory_map.h"
#include "kernel_mmio.h"

#include "layers.h"

#define WORD_SCALE (512 / 32)
#define LOG2_WORD_SIZE 2
#define LSU_WIDTH_SCALE (64 / 32)

#define CORE_ID 1

int main() {

  LSU0_RAM_STRIDE = 1;
  LSU0_RAM_SEG_STRIDE = 1;
  LSU0_RAM_ADDR_OFFSET = 0;
  LSU0_M_OFFSET_HI = 0;
  LSU0_SEG_STRIDE = 0;
  LSU0_SEG_COUNT = 1;

  LSU1_RAM_STRIDE = 1;
  LSU1_RAM_SEG_STRIDE = 1;
  LSU1_RAM_ADDR_OFFSET = 0;
  LSU1_M_OFFSET_HI = 0;
  LSU1_SEG_STRIDE = 0;
  LSU1_SEG_COUNT = 1;

  // second conv3d
  for (int i = 0; i < OFM1_CHN; i+=OFM1_CNT) {
    // fetch ofm
    LSU0_RAM_START_IDX = 24;
    LSU0_RAM_ADDR_OFFSET = 0;
    LSU0_RAM_BLOCK_FACTOR = OFM1_CNT * OFM1_SIZE_CEIL / LSU_WIDTH_SCALE;
    LSU0_RAM_CYCLIC_FACTOR = 1;
    LSU0_M_OFFSET_LO = (OFM1_OFFSET + i * OFM1_SIZE_CEIL) << LOG2_WORD_SIZE;
    LSU0_M_OFFSET_HI = 0xc1;
    LSU0_SEG_STRIDE = 0;
    LSU0_SEG_COUNT = 1;
    LSU0_LEN = OFM1_CNT * OFM1_SIZE_CEIL / WORD_SCALE;
    LSU0_MODE = 1;

    TQ_LSU0_START();
    TQ_LSU0_DONE();

    // fetch weight
    LSU1_RAM_START_IDX = 0;
    LSU1_RAM_ADDR_OFFSET = 0;
    LSU1_RAM_BLOCK_FACTOR = WT1_SIZE_CEIL / LSU_WIDTH_SCALE;
    LSU1_RAM_CYCLIC_FACTOR = NUM_CONV2D_1;

    LSU1_M_OFFSET_LO = (WT1_OFFSET + i * IFM1_CHN * WT1_SIZE_CEIL + 0 * WT1_SIZE_CEIL) << LOG2_WORD_SIZE;
    LSU1_M_OFFSET_HI = 0xc1;
    LSU1_SEG_STRIDE = IFM1_CHN * WT1_SIZE_CEIL / WORD_SCALE;
    LSU1_SEG_COUNT = OFM1_CNT;
    LSU1_LEN = NUM_CONV2D_1 * WT1_SIZE_CEIL / WORD_SCALE;
    LSU1_MODE = 1;

    TQ_LSU1_START();

    // fetch ifm
    LSU0_RAM_START_IDX = 12;
    LSU0_RAM_ADDR_OFFSET = 0;
    LSU0_SEG_STRIDE = 0;
    LSU0_SEG_COUNT = 1;
    LSU0_RAM_BLOCK_FACTOR = IFM1_SIZE_CEIL / LSU_WIDTH_SCALE;
    LSU0_RAM_CYCLIC_FACTOR = NUM_CONV2D_1;

    //LSU0_M_OFFSET_LO = (IFM1_OFFSET + 0 * IFM1_SIZE_CEIL) << LOG2_WORD_SIZE;
    LSU0_M_OFFSET_LO = 0;
    LSU0_M_OFFSET_HI = 0;
    LSU0_LEN = NUM_CONV2D_1 * IFM1_SIZE_CEIL / WORD_SCALE;
    LSU0_MODE = 1 + (1 << 4);

    TQ_LSU0_START();

    TQ_LSU1_DONE();
    TQ_LSU0_DONE();

    int pp = 0;
    for (int j = 0; j < IFM1_CHN; j+=NUM_CONV2D_1) {
      int len = (j < IFM1_CHN_SCALE * NUM_CONV2D_1) ? NUM_CONV2D_1 : (IFM1_CHN - IFM1_CHN_SCALE * NUM_CONV2D_1);

      if (j + NUM_CONV2D_1 < IFM1_CHN) {
      // fetch weight
      LSU1_RAM_START_IDX = 0;
      LSU1_RAM_ADDR_OFFSET = (pp == 0) ? (OFM1_CNT * WT1_SIZE_CEIL / LSU_WIDTH_SCALE) : 0;
      LSU1_RAM_BLOCK_FACTOR = WT1_SIZE_CEIL / LSU_WIDTH_SCALE;
      LSU1_RAM_CYCLIC_FACTOR = NUM_CONV2D_1;

      LSU1_M_OFFSET_LO = (WT1_OFFSET + i * IFM1_CHN * WT1_SIZE_CEIL + (j + NUM_CONV2D_1) * WT1_SIZE_CEIL) << LOG2_WORD_SIZE;
      LSU1_M_OFFSET_HI = 0xc1;
      LSU1_SEG_STRIDE = IFM1_CHN * WT1_SIZE_CEIL / WORD_SCALE;
      LSU1_SEG_COUNT = OFM1_CNT;
      LSU1_LEN = NUM_CONV2D_1 * WT1_SIZE_CEIL / WORD_SCALE;
      LSU1_MODE = 1;

      TQ_LSU1_START();

      // fetch ifm
      LSU0_RAM_START_IDX = 12;
      LSU0_RAM_ADDR_OFFSET = (pp == 0) ? IFM1_SIZE_CEIL / LSU_WIDTH_SCALE : 0;
      LSU0_SEG_STRIDE = 0;
      LSU0_SEG_COUNT = 1;
      LSU0_RAM_BLOCK_FACTOR = IFM1_SIZE_CEIL / LSU_WIDTH_SCALE;
      LSU0_RAM_CYCLIC_FACTOR = NUM_CONV2D_1;

      //LSU0_M_OFFSET_LO = (IFM1_OFFSET + (j + NUM_CONV2D_1) * IFM1_SIZE_CEIL) << LOG2_WORD_SIZE;
      LSU0_M_OFFSET_LO = 0;
      LSU0_M_OFFSET_HI = 0;
      LSU0_LEN = NUM_CONV2D_1 * IFM1_SIZE_CEIL / WORD_SCALE;
      LSU0_MODE = 1 + (1 << 4);

      TQ_LSU0_START();
      }

      KRN_IFM_OFFSET = (pp == 0) ? 0 : IFM1_SIZE_CEIL / LSU_WIDTH_SCALE;
      for (int k = 0; k < OFM1_CNT; k++) {
        KRN_WT_OFFSET = ((pp == 0) ? 0 : (OFM1_CNT * WT1_SIZE_CEIL / LSU_WIDTH_SCALE)) + (k * WT1_SIZE_CEIL / LSU_WIDTH_SCALE);
        KRN_OFM_OFFSET = k * OFM1_SIZE_CEIL / LSU_WIDTH_SCALE;
        KRN_LEN = len;
        KRN_START = 1;
        TQ_CL_START();
        TQ_CL_DONE();
      }

      if (j + NUM_CONV2D_1 < IFM1_CHN) {
        TQ_LSU1_DONE();
        TQ_LSU0_DONE();
      }
      pp = 1 - pp;
    }

    // write ofm
    LSU0_RAM_START_IDX = 24;
    LSU0_RAM_ADDR_OFFSET = 0;
    LSU0_RAM_BLOCK_FACTOR = OFM1_CNT * OFM1_SIZE_CEIL / LSU_WIDTH_SCALE;
    LSU0_RAM_CYCLIC_FACTOR = 1;
    LSU0_M_OFFSET_LO = (OFM1_OFFSET + i * OFM1_SIZE_CEIL) << LOG2_WORD_SIZE;
    LSU0_M_OFFSET_HI = 0xc1;
    LSU0_SEG_STRIDE = 0;
    LSU0_SEG_COUNT = 1;
    LSU0_LEN = OFM1_CNT * OFM1_SIZE_CEIL / WORD_SCALE;
    LSU0_MODE = 2;

    TQ_LSU0_START();
    TQ_LSU0_DONE();
  }

  while (TQ_EMPTY_N == 1);

  CTRL_MAXI_SOCKET_OFFSET_LO = ((SOCKET_MANAGER_NOC_ADDR + MMIO_REGSPACE_OFFSET) & 0xFFFFFFFF) + ((128 + CORE_ID)<<6); 
  CTRL_MAXI_SOCKET_OFFSET_HI = ((SOCKET_MANAGER_NOC_ADDR + MMIO_REGSPACE_OFFSET) >> 32);
  CTRL_MAXI_WRITE = 1;
  while (CTRL_MAXI_WRITE_DONE == 0);

  CPU_STATUS = 1;

  // spin
  for(;;) {
    asm volatile ("nop");
  }
}
